=== 304471720/clearpool/src/main/java/org/opensource/clearpool/configuration/clearpool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clearpool">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="console" minOccurs="0" maxOccurs="1" />
				<xs:choice>
					<xs:element name="distribute-url" type="xs:string"
						minOccurs="1" maxOccurs="unbounded" />
					<xs:group ref="otherElements" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="console">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="port" type="xs:integer" />
				<xs:element name="security" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="user" type="xs:string" />
							<xs:element name="password" type="xs:string" />
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:group name="otherElements">
		<xs:sequence>
			<xs:element name="alias" type="xs:string" maxOccurs="1" />
			<xs:group ref="database" />
			<xs:element name="jta-support" type="xs:boolean"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="core-pool-size" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="max-pool-size" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="acquire-increment" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="acquire-retry-times" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="useless-connection-exception" type="xs:boolean"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="limit-idle-time" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="keep-test-period" type="xs:integer"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="test-table-name" type="xs:string"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="show-sql" type="xs:boolean" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:group>

	<xs:group name="database">
		<xs:choice>
			<xs:element ref="jndi" />
			<xs:element ref="jdbc" />
		</xs:choice>
	</xs:group>

	<xs:element name="jndi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jndi-name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="prop" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType mixed="true">
						<xs:attribute name="key" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="jdbc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jdbc-class" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="url" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="user" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="password" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="security-class" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="file-path" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="status" type="statusType" minOccurs="0"
					maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="encrypt" />
			<xs:enumeration value="decrypt" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 304471720/clearpool/src/test/resources/clearpool/jta/clearpool-test-jta-distributed.xml
<?xml version="1.0" encoding="UTF-8"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
       xsi:noNamespaceSchemaLocation="clearpool.xsd">  
	<console>
		<port>8085</port>
		<security>
			<user>1</user>
			<password>1</password>
		</security>
	</console>
	<distribute-url>clearpool/jta/clearpool-test-jta-distributed1.xml</distribute-url>
	<distribute-url>clearpool/jta/clearpool-test-jta-distributed2.xml</distribute-url>
</clearpool>

=== 304471720/clearpool/src/test/resources/clearpool/jta/clearpool-test-jta-oracle-distributed1.xml
<?xml version="1.0" encoding="UTF-8"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="clearpool.xsd">
	<alias>myclearpool1</alias>
	<jdbc>
		<!-- replace jdbcClass with your database's jdbc-class please -->
		<jdbc-class>oracle.jdbc.driver.OracleDriver</jdbc-class>
		<!-- replace url with your database's url please -->
		<url>jdbc:oracle:thin:@20.10.1.224:1521:ora10g</url>
		<!-- replace user with your database's user please -->
		<user>cm65dev</user>
		<!-- replace password with your database's password please -->
		<password>1</password>
	</jdbc>
	<jta-support>true</jta-support>
	<core-pool-size>10</core-pool-size>
	<max-pool-size>50</max-pool-size>
	<acquire-increment>10</acquire-increment>
	<acquire-retry-times>3</acquire-retry-times>
	<limit-idle-time>5</limit-idle-time>
	<keep-test-period>20</keep-test-period>
	<test-table-name>test</test-table-name>
	<show-sql>false</show-sql>
</clearpool>

=== 304471720/clearpool/src/test/resources/xml/jndi.xml
<?xml version="1.0" encoding="UTF-8"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="clearpool.xsd">
	<console>
		<port>8085</port>
		<security>
			<user>1</user>
			<password>1</password>
		</security>
	</console>
	<alias>jndiclearpool</alias>
	<jndi>
		<jndi-name>jndi</jndi-name>
		<prop key="java.naming.factory.initial">initial</prop>
		<prop key="java.naming.provider.url">url</prop>
		<prop key="java.naming.security.principal">user</prop>
		<prop key="java.naming.security.credentials">password</prop>
	</jndi>
	<core-pool-size>10</core-pool-size>
	<max-pool-size>50</max-pool-size>
	<acquire-increment>5</acquire-increment>
	<acquire-retry-times>3</acquire-retry-times>
	<limit-idle-time>5</limit-idle-time>
	<keep-test-period>20</keep-test-period>
	<test-table-name>test</test-table-name>
	<show-sql>false</show-sql>
</clearpool>

=== 304471720/clearpool/src/main/java/org/opensource/clearpool/configuration/example/clearpool-distributed.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="clearpool.xsd">
	<console>
		<port>8085</port>
		<security>
			<user>1</user>
			<password>1</password>
		</security>
	</console>
	<!-- we get cfgs by distribute-url. -->
	<distribute-url>clearpool-jdbc.xml</distribute-url>
	<distribute-url>clearpool-jndi.xml</distribute-url>
</clearpool>

=== 304471720/clearpool/src/test/resources/clearpool/jta/clearpool-test-jta-unique.xml
<?xml version="1.0" encoding="UTF-8"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="clearpool.xsd">
	<alias>myclearpool</alias>
	<jdbc>
		<jdbc-class>com.mysql.jdbc.Driver</jdbc-class>
		<url>jdbc:mysql://127.0.0.1:3306/test?characterEncoding=gbk</url>
		<user>root</user>
		<password>1</password>
	</jdbc>
	<jta-support>true</jta-support>
	<core-pool-size>10</core-pool-size>
	<max-pool-size>50</max-pool-size>
	<acquire-increment>5</acquire-increment>
	<acquire-retry-times>3</acquire-retry-times>
	<limit-idle-time>5</limit-idle-time>
	<keep-test-period>20</keep-test-period>
	<test-table-name>test</test-table-name>
	<show-sql>true</show-sql>
</clearpool>

=== 304471720/clearpool/src/main/java/org/opensource/clearpool/configuration/example/clearpool-jndi.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<clearpool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="clearpool.xsd">
	<!-- alias -->
	<alias>myclearpool</alias>
	<!-- we can get datasource by jndi.-->
	<jndi>
		<jndi-name>jndi</jndi-name>
		<prop key="java.naming.factory.initial">initial</prop>
		<prop key="java.naming.provider.url">url</prop>
		<prop key="java.naming.security.principal">user</prop>
		<prop key="java.naming.security.credentials">password</prop>
	</jndi>
	<!-- support distributed transaction -->
	<jta-support>true</jta-support>
	<!-- core connection:default value is 0 -->
	<core-pool-size>10</core-pool-size>
	<!-- max connection:default value is Integer.MAX_VALUE -->
	<max-pool-size>50</max-pool-size>
	<!-- we get acquire-increment connection to fill the pool when there is 
		no connection could be used,default value is 1. -->
	<acquire-increment>5</acquire-increment>
	<!-- we try acquire-retry-times times when we get connection fail,default 
		value is 0. -->
	<acquire-retry-times>3</acquire-retry-times>
	<!-- if useless-connection-exception is true,we throw a exception when we 
		get connection from the pool and there is no connection left. -->
	<useless-connection-exception>true</useless-connection-exception>
	<!-- when the connection is more than max-connection and free for more than 
		limit-idle-time(s),it will be released.The default value is 60(s). -->
	<limit-idle-time>60</limit-idle-time>
	<!-- we test if connection is valid during keep-test-period(s), default 
		value is -1 which means we don't have to test the connection. -->
	<keep-test-period>60</keep-test-period>
	<!-- we create keep-test-table to test the connection, default table value 
		is "clearpool_test".Note: suggest that set test-table-name less than 30 chars 
		to support oracle. -->
	<test-table-name>test</test-table-name>
	<!-- we will log the sql after we execute it if we set show-sql true and 
		the log is valid -->
	<show-sql>true</show-sql>
</clearpool>
